import Head from 'next/head'
import {BsMoonStarsFill, BsFillCloudSunFill} from 'react-icons/bs'
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube } from 'react-icons/ai'
import Image from 'next/image'
import dev from '../public/dev-ed-wave.png'
import design from '../public/design.png'
import code from '../public/code.png'
import consulting from '../public/consulting.png'
import web1 from '../public/web1.png'
import web2 from '../public/web2.png'
import web3 from '../public/web3.png'
import web4 from '../public/web4.png'
import web5 from '../public/web5.png'
import web6 from '../public/web6.png'
import { useState } from 'react'

export default function Home() {

const [darkMode, setDarkMode] = useState(false)

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Portfolio Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='dark:bg-gray-900'>
      <main className='container mx-auto px-3'>
        <section className='min-h-screen'>
          <nav className='py-10 flex justify-between'>
            <h1 className='text-xl font-medium md:text-2xl dark:text-white'>developedby<span className='text-teal-500 font-bold'>DEV</span></h1>
            <ul className='flex gap-4 items-center'>
              <li className='text-2xl cursor-pointer transition duration-500 dark:text-white md:text-3xl'>{!darkMode ? <BsMoonStarsFill onClick={()=> setDarkMode(!darkMode)}/> : <BsFillCloudSunFill onClick={()=> setDarkMode(!darkMode)}/> }</li>
              <li><a href="#" className='bg-gradient-to-r from-cyan-500 to-teal-500 py-2 px-4 rounded-md text-white'>Resume</a></li>
            </ul>
          </nav>
          <div className='text-center py-20'>
            <h2 className='text-5xl text-teal-500 font-bold pb-1 md:text-6xl'>John Doe</h2>
            <h3 className='text-2xl text-gray-500 font-medium pb-4 md:text-3xl dark:text-gray-300'>Developer and designer</h3>
            <p className='text-md text-gray-800 leading-8 max-w-3xl mx-auto dark:text-gray-400'>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Explicabo esse laudantium quod nostrum quibusdam labore inventore repellendus. Ducimus, labore et.</p>
          </div>
          <div className='flex justify-center items-center gap-6 text-4xl text-teal-800 md:text-5xl dark:text-gray-100'>
            <AiFillTwitterCircle/>
            <AiFillLinkedin/>
            <AiFillYoutube/>
          </div>
          <div className='relative bg-gradient-to-b from-cyan-500 w-80 h-80 my-20 overflow-hidden rounded-full mx-auto md:w-96 md:h-96'>
            <Image src={dev} width="500" height="500" layout='fill' objectFit='cover' />
          </div>
        </section>
        <section>
            <div>
              <h2 className='text-3xl font-semibold py-5 md:text-4xl dark:text-gray-300'>Service I Offer</h2>
              <p className='text-md text-gray-800 leading-8 mb-4 dark:text-gray-400'>Lorem ipsum dolor, sit amet consectetur adipisicing elit. <span className='text-cyan-500'>Perferendis</span> ea unde minima, <span className='text-cyan-500'>commodi</span> quas ex <span className='text-cyan-500'>aperiam</span> repellendus autem quam facilis! Quo animi ad recusandae sed unde illum minus, in aspernatur?</p>
              <p className='text-md text-gray-800 leading-8 dark:text-gray-400'>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Fugiat, eos!</p>
            </div>
            <div className='grid grid-cols-1 md:grid-cols-3 gap-10'>
              <div className='text-center border border-gray-300 hover:border-teal-600 transition p-10 rounded-xl my-10'>
                <Image src={design} width={100} height={100} />
                <h3 className='text-xl py-5 font-semibold md:text-2xl dark:text-gray-300'>Beautiful Designs</h3>
                <p className='text-md text-gray-800 leading-8 mb-4 dark:text-gray-400'>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, exercitationem?</p>
                <h4 className='text-lg text-teal-500 font-semibold pb-2 md:text-xl'>Design tools i use</h4>
                <p className='text-gray-800 py-1 dark:text-gray-400'>Photoshop</p>
                <p className='text-gray-800 py-1 dark:text-gray-400'>Illustrator</p>
                <p className='text-gray-800 py-1 dark:text-gray-400'>Adobe XD</p>
              </div>
              <div className='text-center border border-gray-300 hover:border-teal-600 transition p-10 rounded-xl my-10'>
                <Image src={consulting} width={100} height={100} />
                <h3 className='text-xl py-5 font-semibold md:text-2xl dark:text-gray-300'>Project Management</h3>
                <p className='text-md text-gray-800 leading-8 mb-4 dark:text-gray-400'>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, exercitationem?</p>
                <h4 className='text-lg text-teal-500 font-semibold pb-2 md:text-xl'>Management tools i use</h4>
                <p className='text-gray-800 py-1 dark:text-gray-400'>Strategy</p>
                <p className='text-gray-800 py-1 dark:text-gray-400'>Management</p>
                <p className='text-gray-800 py-1 dark:text-gray-400'>Quality</p>
              </div>
              <div className='text-center border border-gray-300 hover:border-teal-600 transition p-10 rounded-xl my-10'>
                <Image src={code} width={100} height={100} />
                <h3 className='text-xl py-5 font-semibold md:text-2xl dark:text-gray-300'>Web Development</h3>
                <p className='text-md text-gray-800 leading-8 mb-4 dark:text-gray-400'>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, exercitationem?</p>
                <h4 className='text-lg text-teal-500 font-semibold pb-2 md:text-xl'>Development tools i use</h4>
                <p className='text-gray-800 py-1 dark:text-gray-400'>Html</p>
                <p className='text-gray-800 py-1 dark:text-gray-400'>Css</p>
                <p className='text-gray-800 py-1 dark:text-gray-400'>JavaScript</p>
              </div>
            </div>
          </section>
          <section>
            <div className='py-20'>
              <h2 className='text-3xl font-semibold py-5 md:text-4xl'>Portfolio</h2>
              <div className='grid gap-10 grid-cols-1 md:grid-cols-2'>
                <div>
                  <Image src={web1} width={'100%'} height={'100%'} objectFit="cover" layout='responsive'/>
                </div>
                <div>
                  <Image src={web2} width={'100%'} height={'100%'} objectFit="cover" layout='responsive'/>
                </div>
                <div>
                  <Image src={web3} width={'100%'} height={'100%'} objectFit="cover" layout='responsive'/>
                </div>
                <div>
                  <Image src={web4} width={'100%'} height={'100%'} objectFit="cover" layout='responsive'/>
                </div>
                <div>
                  <Image src={web5} width={'100%'} height={'100%'} objectFit="cover" layout='responsive'/>
                </div>
                <div>
                  <Image src={web6} width={'100%'} height={'100%'} objectFit="cover" layout='responsive'/>
                </div>
              </div>
            </div>
          </section>
      </main>
      </div>
    </div>
  )
}
